---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-mysql
  labels:
    app: sysdigcloud
    role: mysql-router
spec:
  ports:
    - port: 3306
      targetPort: 6446
  selector:
    app: sysdigcloud
    role: mysql-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdigcloud-mysql-router
spec:
  selector:
    matchLabels:
      app: sysdigcloud
      role: mysql-router
  replicas: 1 #3
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: mysql-router
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: app
      #          operator: In
      #          values:
      #          - sysdigcloud
      #        - key: role
      #          operator: In
      #          values:
      #          - mysql-router
      #      topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mysql-router
          image: mysql/mysql-router:8.0.19 #quay.io/sysdig/mysql-router:8.0.16.2
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
              #valueFrom:
              #  configMapKeyRef:
              #    name: sysdigcloud-config
              #    key: mysql.password
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: mysql #sysdigcloud-mysql-cluster
            - name: MYSQL_INNODB_NUM_MEMBERS
              value: "3"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 100Mi
      imagePullSecrets:
        - name: sysdigcloud-pull-secret